server:
  port: 0
spring:
  application:
    name: mycar-client
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/mycar_client
    username: userok
    password: p@ssw0rd
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka